'use strict';
require('./main/main.module');
require('./google-map-data/google-map-data.module');
require('./vacancies/vacancies.module');
require('./news/news.module');
require('./authentication/authentication.module');
require('./user/user.module');
require('./admin/admin.module');
require('./tenders/tenders.module');
require('./about/about.module');
require('./public/public.module');
require('./social-responsibility/social-responsibility.module');
require('./store-addresses/store-addresses.module');
require('./product/product.module');
require('./brands/brands.module');
require('./cities/cities.module');
require('./wishlist/wishlist.module');
require('./cart/cart.module');
require('./localization/localization.module');
// Define the `core` module
angular.module('core', [
  'core.main', 
  'core.google',
  'core.vacancy',
  'core.news',
  'core.authentication',
  'core.user',
  'core.admin',
  'core.tenders',
  'core.about',
  'core.public',
  'core.socialResponsibility',
  'core.storeAddresses',
  'core.product',
  'core.brands',
  'core.cities',
  'core.wishlist',
  'core.cart',
  'core.localization'
]);
